import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import { Sidebar, Header, Footer } from "./layout_components";
import "./globals.css";
import cn from 'classnames';
import styles from './layout.module.css'
import {API} from './api'



const notoSans = Noto_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getMenu (firstCategory: number) {
  const res = await fetch(API.topPage.find, {
    method: 'POST',
    body: JSON.stringify({
      firstCategory
    }),
    headers: new Headers({'content-type': 'application/json'})
  }
  );
  return res.json();
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menu = await getMenu(0)
  console.log(menu)
  return (
    <html lang="en">
    <body className={notoSans.className}>
    <div className={styles.wrapper}>
      <Header className={styles.header}/>
      <Sidebar className={styles.sidebar}/>
      <div className={styles.body}>
        {children}
      </div>
      <Footer className={styles.footer}/>
      </div>
      </body>
    </html>
  );
}
